// THIS FILE IS AUTOGENERATED BY CUGOGEN.
package core

type Metadata struct {
	Name        string
	Description string
}
type ComponentDefinition struct {
	ApiVersion string
	Kind       string
	Metadata   Metadata
	Spec       struct {
		Cue        string
		Jsonschema string
	}
}
type Pattern struct {
	Name     string
	Type     string
	Settings struct {
		ApplyTo string
	}
}
type Component struct {
	Name     string
	Type     string
	Settings map[string]interface{}
}
type Design struct {
	ApiVersion string
	Kind       string
	Metadata   Metadata
	Spec       struct {
		Components []Component
		Patterns   []Pattern
	}
}
type PatternDefinition struct {
	ApiVersion string
	Kind       string
	Metadata   Metadata
	Spec       struct {
		Cue        string
		Jsonschema string
	}
}
